Too many changes.

diff --git a/driller b/driller
--- a/driller
+++ b/driller
@@ -16,18 +16,9 @@ EOF
   exit 0
 }
 
-function find_path_in_arguments() {
-  for arg in "$@"; do
-    if ! [[ ${arg} =~ ^- ]]; then
-      [[ ! -z ${path} ]] && fatal "Only one path should be parsed in."
-      path=${arg}
-    fi
-  done
-
-  [[ -z ${path} ]] && path=$(pwd)
-  [[ ! -e ${path} ]] && fatal "Invalid path"
-
-  echo ${path}
+function __path_valid() {
+  [[ -e $1 ]]
+  return $?
 }
 
 function __strip_extraneous_slashes() {
@@ -57,6 +48,7 @@ function __add_trailing_slash() {
 
 function __clean_path() {
   path=$1
+  __path_valid ${path} || fatal "Invalid path"
   path=$(__qualify_dot_dot_slashes ${path})
   path=$(__strip_extraneous_slashes ${path})
   path=$(__add_trailing_slash ${path})
@@ -72,7 +64,8 @@ function __dirname() {
 }
 
 function __filename() {
-  [[ -f $1 ]] && basename -- $(__clean_path $1)
+  [[ -e $1 ]] && [[ ! -d $1 ]] || fatal "Path isn't to a file"
+  basename -- $(__clean_path $1)
 }
 
 function __scm_dir() {
@@ -90,9 +83,16 @@ function scm_root() {
 }
 
 function debug() {
+  __path_valid ${PATH_ARG} || fatal "Invalid path"
   echo "PATH_ARG:${PATH_ARG}"
   echo "DIR:$(__dirname ${PATH_ARG})"
-  echo "FILE:$(__filename ${PATH_ARG})"
+
+  if [[ -d ${PATH_ARG} ]]; then
+    echo "FILE:"
+  else
+    echo "FILE:$(__filename ${PATH_ARG})"
+  fi
+
   echo "FLAT_PATH:$(__clean_path ${PATH_ARG})"
   exit 0
 }
@@ -107,7 +107,8 @@ function fatal() {
   exit 1
 }
 
-PATH_ARG=$(find_path_in_arguments $@)
+PATH_ARG=$(eval "echo \$$#")                    # the last argument is the file
+set -- $(echo $@ | sed -E "s#${PATH_ARG}\$##")
 
 for arg in "$@"; do
   case "${arg}" in
@@ -115,7 +116,7 @@ for arg in "$@"; do
       __clean_path ${PATH_ARG}
       ;;
     "--basename")
-      __filename ${PATH_ARG} || error "Path isn't to a file"
+      __filename ${PATH_ARG}
       ;;
     "--debug")
       debug
